In [2]:
pip install folium

Collecting folium
  Downloading https://files.pythonhosted.org/packages/b9/05/bb30dc97efa1b431c88deac7a77af3d62df1423574c4fe2d5a10a4932e85/folium-0.12.1.post1-py2.py3-none-any.whl (95kB)
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\avich\anaconda3\lib\site-packages (from folium)
Collecting branca>=0.3.0 (from folium)
  Downloading https://files.pythonhosted.org/packages/61/1f/570b0615c452265d57e4114e633231d6cd9b9d275256778a675681e4f711/branca-0.4.2-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in c:\users\avich\anaconda3\lib\site-packages (from folium)
Requirement already satisfied (use --upgrade to upgrade): jinja2>=2.9 in c:\users\avich\anaconda3\lib\site-packages (from folium)
Requirement already satisfied (use --upgrade to upgrade): idna<3,>=2.5 in c:\users\avich\anaconda3\lib\site-packages (from requests->folium)
Requirement already satisfied (use --upgrade to upgrade): urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\avich\anaconda3\lib\site-packages (from requests->folium)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in c:\users\avich\anaconda3\lib\site-packages (from requests->folium)
Requirement already satisfied (use --upgrade to upgrade): chardet<4,>=3.0.2 in c:\users\avich\anaconda3\lib\site-packages (from requests->folium)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.23 in c:\users\avich\anaconda3\lib\site-packages (from jinja2>=2.9->folium)
Note: you may need to restart the kernel to use updated packages.Installing collected packages: branca, folium
Successfully installed branca-0.4.2 folium-0.12.1.post1

In [1]:
import folium
coords = (46.539758, 2.430331)
map = folium.Map(location=coords, tiles='OpenStreetMap', zoom_start=6)

In [2]:
map

pour ajouter des cercles sur la cartes

In [ ]:
for i in range(len(#ACCIDENT)):
    folium.CircleMarker(
        location = (LATS[i], LONGS[i]),
        radius = TEMPS[i]*2,
        color = 'crimson',
        fill = True,
        fill_color = 'crimson'
    ).add_to(map)

In [ ]:
pour colorer les cercles colormap

In [ ]:
import folium, branca

coords = (46.539758, 2.430331)
map = folium.Map(location=coords, tiles='OpenStreetMap', zoom_start=6)

cm = branca.colormap.LinearColormap(['blue', 'red'], vmin=min(#NB_ACCIDENT), vmax=max(#NB_ACCIDENT))
map.add_child(cm) # add this colormap on the display

for elem1,elem2,.. in zip(var1, var2,..):
    folium.CircleMarker(
        location=[lat, long],
        radius=size,
        color=cm(color),
        fill=True,
        fill_color=cm(color),
        fill_opacity=0.6
    ).add_to(map)

map.save(outfile='map.html')

In [4]:
import pandas as pd

In [19]:
df_utiles = pd.read_csv('df_utiles.csv')

In [20]:
df_utiles

,Unnamed: 0,jour,mois,an,hrmn,lum,dep,agg,int,atm,...,situ,vma,senc,catv,obs,obsm,choc,manv,motor,presence_deces
0,0,30,11,2019,60,4,93,1,1,1,...,1,70,2,7,0,2,5,23,1,0
1,1,30,11,2019,60,4,93,1,1,1,...,1,70,2,7,0,2,5,23,1,0
2,2,30,11,2019,60,4,93,1,1,1,...,1,70,2,17,1,0,3,11,1,0
3,3,30,11,2019,120,3,93,1,1,1,...,1,70,1,7,4,0,1,0,1,0
4,4,28,11,2019,900,1,92,1,1,1,...,1,90,1,7,0,2,1,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132972,132972,27,11,2019,420,1,67,1,1,8,...,1,90,1,7,0,2,1,2,1,0
132973,132973,30,11,2019,120,4,94,1,1,1,...,1,90,2,7,3,0,1,21,0,0
132974,132974,30,11,2019,900,1,78,1,1,1,...,1,50,2,33,0,0,7,1,1,0
132975,132975,29,11,2019,1200,3,92,1,1,1,...,2,110,1,10,0,2,4,0,2,0
132976,132976,29,11,2019,1200,3,92,1,1,1,...,2,110,1,10,0,2,1,0,1,0

In [21]:
df_utiles.head()

,Unnamed: 0,jour,mois,an,hrmn,lum,dep,agg,int,atm,...,situ,vma,senc,catv,obs,obsm,choc,manv,motor,presence_deces
0,0,30,11,2019,60,4,93,1,1,1,...,1,70,2,7,0,2,5,23,1,0
1,1,30,11,2019,60,4,93,1,1,1,...,1,70,2,7,0,2,5,23,1,0
2,2,30,11,2019,60,4,93,1,1,1,...,1,70,2,17,1,0,3,11,1,0
3,3,30,11,2019,120,3,93,1,1,1,...,1,70,1,7,4,0,1,0,1,0
4,4,28,11,2019,900,1,92,1,1,1,...,1,90,1,7,0,2,1,2,1,0

In [22]:
df_utiles.describe()

,Unnamed: 0,jour,mois,an,hrmn,lum,dep,agg,int,atm,...,situ,vma,senc,catv,obs,obsm,choc,manv,motor,presence_deces
count,132977.00000,132977.000000,132977.000000,132977.0,132977.000000,132977.000000,132977.000000,132977.000000,132977.000000,132977.000000,...,132977.000000,132977.000000,132977.000000,132977.000000,132977.000000,132977.000000,132977.000000,132977.000000,132977.000000,132977.000000
mean,66488.00000,15.679546,6.701587,2019.0,811.744587,1.932710,113.289840,1.622596,2.016552,1.614279,...,1.328350,61.545861,1.560819,12.204983,1.120036,1.543244,2.912804,7.202343,1.149943,0.026305
std,38387.29771,8.746306,3.385577,0.0,329.302835,1.495194,221.949146,0.484739,1.982705,1.672985,...,1.135905,25.020834,0.832060,12.339295,3.263113,1.089174,2.391689,8.113968,1.054699,0.160042
min,0.00000,1.000000,1.000000,2019.0,0.000000,1.000000,1.000000,1.000000,1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,33244.00000,8.000000,4.000000,2019.0,540.000000,1.000000,34.000000,1.000000,1.000000,1.000000,...,1.000000,50.000000,1.000000,7.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
50%,66488.00000,16.000000,7.000000,2019.0,840.000000,1.000000,69.000000,2.000000,1.000000,1.000000,...,1.000000,50.000000,1.000000,7.000000,0.000000,2.000000,2.000000,2.000000,1.000000,0.000000
75%,99732.00000,23.000000,10.000000,2019.0,1080.000000,3.000000,87.000000,2.000000,2.000000,1.000000,...,1.000000,80.000000,2.000000,10.000000,0.000000,2.000000,4.000000,15.000000,1.000000,0.000000
max,132976.00000,31.000000,12.000000,2019.0,1380.000000,5.000000,999.000000,2.000000,9.000000,9.000000,...,8.000000,800.000000,3.000000,99.000000,17.000000,9.000000,9.000000,26.000000,6.000000,1.000000

In [26]:
df_utiles["presence_deces"].describe()

count    132977.000000
mean          0.026305
std           0.160042
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: presence_deces, dtype: float64

2,6% des accidents ont causé un décès

In [28]:
df_utiles["grav"].describe()

count    132977.000000
mean          2.542635
std           1.371815
min           1.000000
25%           1.000000
50%           3.000000
75%           4.000000
max           4.000000
Name: grav, dtype: float64

In [30]:
df_utiles["sexe"].describe()

count    132977.000000
mean          1.320304
std           0.466595
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max           2.000000
Name: sexe, dtype: float64

68% des accidents sont causés par des hommes

In [36]:
df_utiles["vma"].describe()

count    132977.000000
mean         61.545861
std          25.020834
min          -1.000000
25%          50.000000
50%          50.000000
75%          80.000000
max         800.000000
Name: vma, dtype: float64

In [ ]:
df_accidents2020 = pd.read_csv('caracteristiques-2020.csv', sep=";")
df_usagers2020 = pd.read_csv('usagers-2020.csv', sep=";")
df_lieux2020 = pd.read_csv('lieux-2020.csv', sep=";")
df_vehicules2020 = pd.read_csv('vehicules-2020.csv', sep=";")
df_test2020 = df_accidents2020.merge(df_usagers2020.merge(df_lieux2020.merge(df_vehicules2020))) #dataframe à traiter

In [ ]:
df_utiles2020 = df_test2020.drop(axis=1, labels=['Num_Acc', 'com', 'adr', 'v1', 'id_vehicule', 'num_veh', 'lartpc', 'larrout', 'occutc', 'v2', 'voie'])
df_utiles2020 = df_utiles2020.dropna()
df_utiles2020["hrmn"] = pd.to_datetime(df_utiles2020["hrmn"], format='%H:%S')
df_utiles2020["hrmn"] = df_utiles2020["hrmn"].apply(lambda x: int(x.hour)*60 + int(x.minute))

je continue demain